#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE auth_db;
    CREATE DATABASE authoriz_db;
    CREATE DATABASE core_db;
    GRANT ALL PRIVILEGES ON DATABASE auth_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE authoriz_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE core_db TO $POSTGRES_USER;
EOSQL
